### ISSUE TITLE
"j" during operator use

### ISSUE THREAD

**Issue by phmarek** [goldfeld/vim-seek#1]
Without seek.vim the normal mode command "y5j" yanks 5 lines; with seek, this does no longer work.

Of course, "y5y" still does that; but at least it disturbs some muscle memory.

Furthermore, shouldn't the operator motions work in visual mode, too?

**Comment by goldfeld** [comment]
Good knowing this, I'll add a check so that if it's taking a count, it doesn't use the seek functionality. Since we're at it, do you think that 'j' was a good pick? Have you another key to suggest?

**Comment by phmarek** [comment]
No, IMO "j" is not good.
But I didn't think about alternatives...

"J" might be better, or perhaps "o"? I don't think that having a backwards seek is that important, at least as soon as ";" and/or "," work.

**Comment by goldfeld** [comment]
You're right, I have just realized that `dj` is the quickest way to delete a pair of lines, one less keystroke than `2dd` (thanks for that!). Hm, `o` is not a bad suggestion--and then there's also `r`, which is a good mnemonic for 'remote', and I'm planning on a special remote yank motion that's gonna be quite nice. I'll probably make `r` the default but use `o` myself.

By the way, the problem with `,` is that most people map it to `<Leader>`, so people tend to need a backward search so that they can use `;` to keep going backwards.
